### ISSUE TITLE
I like the idea, but can't try on my Mac OS

### ISSUE THREAD

**Issue by ravivooda** [dellis23/ispy#1]
It says `--fork option is not supported by your OS, sorry!`

**Comment by dellis23** [comment]
Unfortunately, as mentioned in the readme, OSX isn't supported.  I'll be happy to accept pull requests for workarounds if you or someone else wants to work on it though.

**Comment by ravivooda** [comment]
Ohh sorry! I somehow skipped that line. I'm trying some alternatives. Will let you know if I find any. Thanks
